name: Test matrix in reusable workflow

on:
  workflow_call:

jobs:
  matrix-test:
    strategy:
      fail-fast: false
      matrix:
        cluster: [dev-ru, dev-eu]
    runs-on: muxly-${{ matrix.cluster }}
    steps:
      - run: echo "matrix.cluster=${{ matrix.cluster }}"
